### PR TITLE
Material Design, UI and UX improvements and quite a lot of bugfixes

### LINKED ISSUE #42: Doesn't remember last screen
When switching to another app and then returning to QuasselDroid by any means including notification entry, the chats list is displayed instead of last used chat/screen. This is annoying if you're watching conversation in one chat and each time you switch to QuasselDroid, you have to select it instead of just seeing what happend till last time you looked.

### PR DESCRIPTION
**Pull request by justjanne**
This is probably the largest Pull Request here yet, I should have split it up into multiple seperate ones, but it was easier to do this way.

[**Screenhots**](http://imgur.com/a/bYHz6)
[**APKs**](https://github.com/justjanne/QuasselDroid/releases)

Here’s a summary of the changes this Pull Request does:
## UI:
- Replaced ActionBarSherlock with the new AppCompat implementation
- Added DetailFragment as a right navigation drawer for QueryBuffers
- Changed the whole UI to use Material Design.
- Updated Notifications
- Replaced most icons with new ones from @oppoyu and Android Lollipop default icons
- Rewrote sender color system
- Added Tablet UI
## Misc:
- Made a lot of stuff more modular, allowing for easier modification
- Moved **ALL** strings out of the code into the strings.xml, also sorted that file properly to make translations easier
- Added support for automated Travis building and testing
## Bugfixes:
- Fixed Notifications: #180 and #26, ~~hopefully~~ confirmed #195 
- Fixed Multiline-input: #181 
- Fixed NickCompletion: #57
- Fixed #42 (partially) by saving the last state in the app, this stores the state beyond reconnect, but the state is lost at reboot of the phone
- Fixed UI bugs #76, #40, #99
- Fixed a lot of reconnect bugs, including #105, #114 and #146, but also multiple ones that weren’t even tracked yet
- Fixed a bug where, upon joining a new channel, the client would show a random other channel instead.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I literally had uninstalled a different IRC client because they Material'd it. I will curse this pull request to the end of time.

**Comment by justjanne** [comment]
Hi @ocdtrekkie :)
Constructive criticism would be appreciated, because we’d like to have the app usable for everyone.
Could you elaborate which changes specifically you don’t like?

We’d like appreciate such feedback :)

(Btw, you can always drop in on #quasseldroid)

**Comment by ocdtrekkie** [comment]
The constructive advice:

It is non-ideal to force everyone to use a theme that is only used by 1.5% of devices right now. (Source: http://developer.android.com/about/dashboards/index.html#Platform) Compared to the 90.6% of devices currently running with a Holo interface.

Unfortunately, the size of the pull request in question means it's likely impossible for me to even get back to the Holo style via forking without losing all of the other fixes and changes since this PR.

Since it already seems to have theme selection, it would be ideal if Holo could be re-implemented as an option.

**Comment by justjanne** [comment]
Re-Implementing Holo is not an option, as all the support libraries don’t allow it. This means we’d have to keep two copies of our whole UI, with all the different bugs that exist in both libraries.

Also, while the Material version would run 2.3.7+, Holo only runs properly 4.0+, so we’d have to deal with that as well, probably by using yet another support library.

And then again, most apps already use material, and the guidelines recommend using material even on Gingerbread devices, so it would look out of place again.

Tbh, it’s already enough of a problem to provide the current UI everywhere, it would only get worse with yet another such design.

**Comment by ocdtrekkie** [comment]
I guess I'll just eat any bugs and use the newest Holo version in perpetuity.

**Pull request merged**
